### ISSUE TITLE
igc vlan doesn't work

### ISSUE THREAD

**Issue by csantanapr** [ibm-garage-cloud/ibm-garage-cloud-cli#13] opened 2020-03-08 17:55 UTC
Install `igc`
```
npm i -g @ibmgaragecloud/cloud-native-toolkit-cli
```

Login into ibmcloud cli

Run the command
```
igc vlan -h
⠼ Getting zones
```
exits with `1`
```
echo $?
1
```

version `0.4.8`
```
0.4.8
```

**Comment by seansund** [comment] 2020-03-09 15:35
Enhance to be smarter and more interactive

**Comment by davesteinberg** [comment] 2020-03-31 19:01
@seansund Is this a matter of enhancement, or is it just plain broken? Is it currently working for you? I seem to recall that it worked fine before and now it's just crashing for me, as @csantanapr describes.

**Comment by davesteinberg** [comment] 2020-03-31 19:03
Oh, I just saw #9. Isn't this just a dupe of that?

**Closed** 2020-06-01 22:10 UTC
Labels: bug
